# Generated by Django 4.2.7 on 2023-11-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
    ]
